export const showError = (conn) => (s) => () => conn.window.showErrorMessage(s);
export const showErrorWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showErrorMessage(s, ...actions);
export const showWarning = (conn) => (s) => () => conn.window.showWarningMessage(s);
export const showWarningWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showWarningMessage(s, ...actions);
export const showInformation = (conn) => (s) => () => conn.window.showInformationMessage(s);
export const showInformationWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showInformationMessage(s, ...actions);
export const createWorkDoneProgressImpl = (conn) => () => conn.window.createWorkDoneProgress();
export const workDone = (reporter) => () => reporter.done();
export const workBegin = (reporter) => ({ title }) => () => reporter.begin(title, undefined, undefined, true);
export const report = (reporter) => (percentage) => () => reporter.report(percentage);
export const reportMsg = (reporter) => (msg) => () => reporter.report(msg);
export const report2 = (reporter) => (percentage) => (msg) => () => reporter.report(percentage, msg);
