name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nwolverson/setup-purescript@ff0795267bfc3408ed3a4ffeaa69f78c512d187b
        with:
          purescript: "0.15.14"
          spago: "latest"

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: "12"

      - name: Install dependencies
        run: |
          npm ci --no-optional

      - name: Build source
        run: npm run-script build
